microsoft/FeaturizersLibrary

CI/CI.yaml
CI/PR.yaml
CI/templates/BuildAndTest.job_template.yaml
CI/templates/BuildAndTest.prologue_stage_template.yaml
CI/templates/_job_template.yaml

Using custom Windows build agents to decrease overall build time. Changes to use custom Linux agents will come as a separate checkin.

Updates for custom build agents

---

src/Traits.h
src/UnitTests/Traits_UnitTest.cpp

Traits<std::chrono::time_point> ToString and FromString for ISO8601 format complete

ToString FromString Complete

---

CI/CI.yaml
CI/PR.yaml
CI/templates/_job_template.yaml
Libraries/Python/DataPipelines/v1.0/DataPipelines/CppToJson/IntegrationTests/CppToJson_IntegrationTest.py-ignore
Libraries/Python/DataPipelines/v1.0/DataPipelines/CppToJson/UnitTests/CppToJson_UnitTest.py-ignore

Using custom linux agents to decrease build times

Using custom Linux agent pool

---

src/Featurizers/Components/Details/EstimatorTraits.h
src/Featurizers/Components/Details/PipelineExecutionEstimatorImpl_details.h
src/Featurizers/Components/GrainEstimatorImpl.h
src/Featurizers/Components/TrainingOnlyEstimatorImpl.h
src/Featurizers/Components/UnitTests/CMakeLists.txt
src/Featurizers/Components/UnitTests/GrainEstimatorImpl_UnitTest.cpp

This Estimator wrapper maintains grain-specific (aka unique key) estimators and transformers.

Adding GrainEstimatorImpl and unit tests

---

src/Featurizer.h

fixed memory leak in callback function

fixed memory leak in callback function

---

src/Featurizers/Components/TrainingOnlyEstimatorImpl.h
src/Featurizers/Components/UnitTests/TrainingOnlyEstimatorImpl_UnitTest.cpp

TraningOnlyEstimatorImpl policies can optionally implement a `begin_training` method if they require annotations produced by other estimators.

Optional `begin_training` policy method with TrainingOnlyEstimatorImpl

---

CI/templates/BuildAndTest.steps_template.yaml
src/Featurizers/Components/UnitTests/InferenceOnlyFeaturizerImpl_UnitTest.cpp
src/Featurizers/Components/code_coverage.yaml
src/Featurizers/code_coverage.yaml
src/code_coverage.yaml

Added coverage files

---

src/Tools/CodeGenerator/Plugins/OnnxRuntimePlugin.py

updates based on Dmitri's comments.
Removed generation of automl_featurizers.s
Fixed filepaths now that we are a cmake "submodule"
Fixed void issue

Updates to ORT Codegen

---

src/Tools/CodeGenerator/Plugins/OnnxRuntimePlugin.py
src/Tools/CodeGenerator/Plugins/OnnxRuntimePluginImpl/StandardCustomStructInfo.py

Removed _t from float and double
removed output type from definition.
No formatting changes in this pr.

More ORT generation fixes

---

src/SharedLibrary/GeneratedCode/SharedLibrary_Common.h
src/Tools/CodeGenerator/Plugins/OnnxRuntimePlugin.py
src/Tools/CodeGenerator/Plugins/OnnxRuntimePluginImpl/CustomStructInfo.py
src/Tools/CodeGenerator/Plugins/OnnxRuntimePluginImpl/StandardCustomStructInfo.py

A zipped file that contains output files that can be diff'd for comparison is available at https://microsoft-my.sharepoint.com/:u:/p/broda/EXKF3oeTaD5IujNXTmoB9IEBjcB3cZ9aCFCdtPYkjTlnzA?e=vysSEh (unfortunately, this link is internal to Microsoft).

Updates to match hand written code

---

src/3rdParty/optional.h
src/Featurizers/Components/DocumentStatisticsEstimator.h
src/Featurizers/Components/MaxAbsValueEstimator.h
src/Featurizers/Components/MinMaxEstimator.h
src/Featurizers/Components/ModeEstimator.h
src/Featurizers/Components/NormUpdaters.h
src/Featurizers/Components/RobustScalarNormEstimator.h
src/Featurizers/Components/StandardDeviationEstimator.h
src/Featurizers/Components/StatisticalMetricsEstimator.h
src/Featurizers/Components/TimeSeriesImputerTransformer.h
src/Featurizers/Components/TimeSeriesMedianEstimator.h
src/Featurizers/Components/UnitTests/HistogramEstimator_UnitTest.cpp
src/Featurizers/Components/UnitTests/IndexMapEstimator_UnitTest.cpp
src/Featurizers/MinMaxScalarFeaturizer.h
src/Featurizers/StandardScaleWrapperFeaturizer.h
src/SharedLibrary/IntegrationTests/GeneratedCode/SharedLibraryTests_CatImputerFeaturizer.h
src/SharedLibrary/IntegrationTests/GeneratedCode/SharedLibraryTests_ImputationMarkerFeaturizer.h
src/SharedLibrary/IntegrationTests/GeneratedCode/SharedLibraryTests_MissingDummiesFeaturizer.h
src/SharedLibrary/SharedLibrary_TimeSeriesImputerFeaturizer.cpp
src/Tools/CodeGenerator/Plugins/SharedLibraryTestsPluginImpl/ScalarTypeInfoFactories.py
src/Tools/CodeGenerator/Plugins/SharedLibraryTestsPluginImpl/StringTypeInfoFactory.py
src/Traits.h
src/UnitTests/Traits_UnitTest.cpp

Clarified support of nullable types in Featurizers and Featurizers/Components. This work was necessary for upcoming work foe featurizers that leverage this functionality.

Updates for better support of nullable types

---

src/SharedLibrary/GeneratedCode/SharedLibrary_StandardScaleWrapperFeaturizer.cpp
src/SharedLibrary/GeneratedCode/SharedLibrary_StandardScaleWrapperFeaturizer.h
src/SharedLibrary/IntegrationTests/CMakeLists.txt
src/SharedLibrary/IntegrationTests/GeneratedCode/SharedLibraryTests_StandardScaleWrapperFeaturizer.h
src/SharedLibrary/IntegrationTests/SharedLibrary_SSWFeaturizer_IntegrationTest.cpp
src/SharedLibrary/cmake/Featurizers.cmake
src/Tools/CodeGenerator/Featurizers.yaml

Finish SSW shared library implementation

StandardScaleWrapper shared library implementation

---

src/Featurizers/Components/ImputerTransformer.h
src/Featurizers/Components/StatisticalMetricsEstimator.h
src/Featurizers/Components/UnitTests/CMakeLists.txt
src/Featurizers/Components/UnitTests/ImputerTransformer_UnitTest.cpp
src/Featurizers/MinMaxImputerFeaturizer.h
src/Featurizers/TestHelpers.h
src/Featurizers/UnitTests/CMakeLists.txt
src/Featurizers/UnitTests/MinMaxImputerFeaturizer_UnitTest.cpp
src/Featurizers/cmake/FeaturizersCode.cmake

- Added Components/ImputerTransformer, which will be used by other ImputerFeaturizers coming soon

Added MinMaxImputerFeaturizer

---

src/Featurizers/Components/NormUpdaters.h
src/Featurizers/Components/StatisticalMetricsEstimator.h
src/Featurizers/Components/UnitTests/StatisticalMetricsEstimator_UnitTest.cpp
src/Featurizers/MeanImputerFeaturizer.h
src/Featurizers/UnitTests/CMakeLists.txt
src/Featurizers/UnitTests/MeanImputerFeaturizer_UnitTest.cpp
src/Featurizers/UnitTests/MinMaxImputerFeaturizer_UnitTest.cpp
src/Featurizers/UnitTests/StandardScaleWrapperFeaturizer_UnitTest.cpp
src/Featurizers/cmake/FeaturizersCode.cmake

Featurizer that imputes null values with the mean (average) of all values encountered during training.

MeanImputerFeaturizer

---

src/Featurizers/CatImputerFeaturizer.h
src/Featurizers/Components/DocumentStatisticsEstimator.h
src/Featurizers/Components/GrainEstimatorImpl.h
src/Featurizers/Components/IndexMapEstimator.h
src/Featurizers/Components/ModeEstimator.h
src/Featurizers/Components/OrderEstimator.h
src/Featurizers/Components/UnitTests/CMakeLists.txt
src/Featurizers/Components/UnitTests/ModeEstimator_UnitTest.cpp
src/Featurizers/Components/UnitTests/OrderEstimator_UnitTest.cpp
src/Featurizers/ModeImputerFeaturizer.h
src/Featurizers/TestHelpers.h
src/Featurizers/UnitTests/CMakeLists.txt
src/Featurizers/UnitTests/ModeImputerFeaturizer_UnitTest.cpp
src/Featurizers/cmake/FeaturizersCode.cmake
src/Traits.h
src/UnitTests/Traits_UnitTest.cpp

Featurizer that sets null values to the most frequently encountered value during training.

ModeImputerFeaturizer

---

src/Tools/CodeGenerator/Featurizers.yaml

CategoryBinarizerFeaturizer is a combination if ModeImputer and OneHotEncoder.

Removed CategoryBinarizerFeaturizer

---

src/Microsoft.Featurizer-cpp.doxygen
src/Microsoft.Featurizer-csharp.doxygen
src/Microsoft.Featurizer-python.doxygen

No longer processing 3rdParty library, which was increasing build times.

Updated doxygen files to reduce build times

---

src/Featurizers/Structs.h

add move constructor and move assignment for SparseVectorEncoding

Add move ctor and assignment

---

src/SharedLibrary/GeneratedCode/SharedLibrary_PCAFeaturizer.cpp
src/SharedLibrary/GeneratedCode/SharedLibrary_PCAFeaturizer.h
src/SharedLibrary/GeneratedCode/SharedLibrary_TruncatedSVDFeaturizer.cpp
src/SharedLibrary/GeneratedCode/SharedLibrary_TruncatedSVDFeaturizer.h
src/SharedLibrary/IntegrationTests/CMakeLists.txt
src/SharedLibrary/IntegrationTests/GeneratedCode/SharedLibraryTests_PCAFeaturizer.h
src/SharedLibrary/IntegrationTests/GeneratedCode/SharedLibraryTests_TruncatedSVDFeaturizer.h
src/SharedLibrary/IntegrationTests/SharedLibrary_PCAFeaturizer_IntegrationTest.cpp
src/SharedLibrary/IntegrationTests/SharedLibrary_TruncatedSVDFeaturizer_IntegrationTest.cpp
src/SharedLibrary/cmake/Featurizers.cmake
src/Tools/CodeGenerator/Featurizers.yaml
src/Tools/CodeGenerator/Plugins/MLNetPlugin.py
src/Tools/CodeGenerator/Plugins/MLNetPluginImpl/MatrixTypeInfoFactory.py
src/Tools/CodeGenerator/Plugins/SharedLibraryPlugin.py
src/Tools/CodeGenerator/Plugins/SharedLibraryPluginImpl/MatrixTypeInfoFactory.py
src/Tools/CodeGenerator/Plugins/SharedLibraryTestsPlugin.py
src/Tools/CodeGenerator/Plugins/SharedLibraryTestsPluginImpl/MatrixTypeInfoFactory.py
src/Tools/CodeGenerator/Plugins/SharedLibraryTestsPluginImpl/ScalarTypeInfoFactories.py
src/Tools/CodeGenerator/__main__.py

Exporting:
- PCAFeaturizer
- TruncatedSVDFeaturizer

Added Matrix support to SharedLibrary

---

src/Featurizers/Components/DocumentStatisticsEstimator.h
src/Featurizers/Components/UnitTests/DocumentStatisticsEstimator_UnitTest.cpp

add a decorate function in DocumentStatisticsFeaturizer

add common function

---

src/Featurizers/Components/DocumentStatisticsEstimator.h
src/Featurizers/CountVectorizerFeaturizer.h
src/Featurizers/UnitTests/CMakeLists.txt
src/Featurizers/UnitTests/CountVectorizerFeaturizer_UnitTests.cpp
src/Featurizers/cmake/FeaturizersCode.cmake

CountVectorizerFeaturizer finished. Duplicate code removed.

CountVectorizerFeaturizer

---

.gitmodules

1. change eigen submodule version(stay same with ort)
2. add google/re2 for potential replacement of <eigen>

change eigen submodule version and introduce google/re2 submodule

---

src/Featurizers/Calculators/Calculators.h
src/Featurizers/Calculators/UnitTests/CMakeLists.txt
src/Featurizers/Calculators/UnitTests/Calculators_UnitTest.cpp
src/Featurizers/Calculators/cmake/FeaturizersCalculatorsCode.cmake
src/Featurizers/Calculators/code_coverage.yaml

Calculators process streaming data; L1-, L2-, and Max-NormUpdaters will be refactored to this concept and new featurizer functionality will use this concept as well.

Added Calculators namespace, functionality,  and build scaffolding

---

src/Featurizers/Components/FrequencyEstimator.h
src/Featurizers/Components/GlobalMinimumFrequencyEstimator.h

Removed unused constructor.
Moved grain featurizer name.

Small fixes not in the original PR

---

src/Featurizers/Components/FilterFeaturizerImpl.h
src/Featurizers/Components/UnitTests/FilterDecoratorFeaturizer_UnitTest.cpp
src/Featurizers/Components/UnitTests/FilterFeaturizerImpl_UnitTest.cpp

Added a custom move constructor to properly set the internal reference

---

src/Featurizers/AnalyticalRollingWindowFeaturizer.h
src/Featurizers/SimpleRollingWindowFeaturizer.h

Fixed memory bug with the double lambda and std::move.

fixed memory bug

---

src/Featurizers/ForecastingPivotFeaturizer.h
src/Featurizers/UnitTests/ForecastingPivotFeaturizer_UnitTests.cpp

Modify InputType of ForecastingPivotFeaturizer with Eigen::Map for better interfacing with raw buffers

Modify InputType of ForecastingPivotFeaturizer with Eigen::Map for better interfacing with raw buffers

---

src/Featurizers/ShortGrainDropperFeaturizer.cpp
src/Featurizers/ShortGrainDropperFeaturizer.h
src/Featurizers/UnitTests/ShortGrainDropperFeaturizer_UnitTests.cpp
src/SharedLibrary/GeneratedCode/SharedLibrary_ShortGrainDropperFeaturizer.cpp
src/SharedLibrary/GeneratedCode/SharedLibrary_ShortGrainDropperFeaturizer.h
src/SharedLibrary/IntegrationTests/CMakeLists.txt
src/SharedLibrary/IntegrationTests/GeneratedCode/SharedLibraryTests_ShortGrainDropperFeaturizer.h
src/SharedLibrary/IntegrationTests/SharedLibrary_ShortGrainDropper_IntegrationTest.cpp
src/SharedLibrary/cmake/Featurizers.cmake
src/Tools/CodeGenerator/Featurizers.yaml

- Changed ShortGrainDropper to keep a list of grains that should be kept
- Generating C Interfaces

ShortGrainDropper updates and C Interfaces

---

src/Archive.h
src/Featurizers/AnalyticalRollingWindowFeaturizer.h
src/Featurizers/Components/GrainFeaturizerImpl.h
src/Featurizers/Components/UnitTests/GrainFeaturizerImpl_UnitTest.cpp
src/Featurizers/LagLeadOperatorFeaturizer.h
src/Featurizers/SimpleRollingWindowFeaturizer.h
src/Traits.h
src/UnitTests/Archive_UnitTest.cpp
src/UnitTests/Traits_UnitTest.cpp

Deserialized GrainTransformers without training can now create Transformers for new grains without providing a transformer creation function.

Transformer creation for GrainTransformer
